[meta]
name     = "Tic Tac GO!"
author   = "XertroV"
category = "Game"
version  = "0.2.2"
siteid   = 285

[script]
#__DEFINES__
# dependencies = ["MLHook", "MLFeedRaceData", "VehicleState", "Camera"]
module = "CGF"
